create table league
(
    id       integer generated by default as identity
        constraint pk_league
            primary key,
    name     varchar(255),
    type     varchar(255),
    logo_url varchar(255),
    rapid_id integer
);


create table team
(
    id        integer generated by default as identity
        constraint pk_team
            primary key,
    name      varchar(255),
    code      varchar(255),
    country   varchar(255),
    founded   integer,
    national  boolean,
    logo_url  varchar(255),
    rapid_id  integer,
    league_id integer
        constraint fk_team_on_leagueid
            references league
);

create table player
(
    id          integer generated by default as identity
        constraint pk_player
            primary key,
    name        varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    age         integer,
    nationality varchar(255),
    injured     boolean,
    photo_url   varchar(255),
    rapid_id    integer
        constraint uc_player_rapidid
            unique,
    team_id     integer
        constraint fk_player_on_teamid
            references team,
    height      varchar(255),
    weight      varchar(255)
);

INSERT INTO league (id, name, type, logo_url, rapid_id) VALUES (14, 'Premier League', 'League', 'https://media.api-sports.io/football/leagues/39.png', 39);
INSERT INTO team (id, name, code, country, founded, national, logo_url, rapid_id, league_id) VALUES (1, 'Manchester United', 'MUN', 'England', 1878, false, 'https://media.api-sports.io/football/teams/33.png', 33, 14);
INSERT INTO team (id, name, code, country, founded, national, logo_url, rapid_id, league_id) VALUES (2, 'Newcastle', 'NEW', 'England', 1892, false, 'https://media.api-sports.io/football/teams/34.png', 34, 14);



