create table league
(
    id       integer generated by default as identity
        constraint pk_league
            primary key,
    name     varchar(255),
    type     varchar(255),
    logo_url varchar(255),
    rapid_id integer
);


create table team
(
    id        integer generated by default as identity
        constraint pk_team
            primary key,
    name      varchar(255),
    code      varchar(255),
    country   varchar(255),
    founded   integer,
    national  boolean,
    logo_url  varchar(255),
    rapid_id  integer,
    league_id integer
        constraint fk_team_on_leagueid
            references league
);

create table player
(
    id          integer generated by default as identity
        constraint pk_player
            primary key,
    name        varchar(255),
    first_name  varchar(255),
    last_name   varchar(255),
    age         integer,
    nationality varchar(255),
    injured     boolean,
    photo_url   varchar(255),
    rapid_id    integer
        constraint uc_player_rapidid
            unique,
    team_id     integer
        constraint fk_player_on_teamid
            references team,
    height      varchar(255),
    weight      varchar(255)
);
