CREATE TABLE team
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    code     VARCHAR(255),
    country  VARCHAR(255),
    founded  INTEGER,
    national BOOLEAN,
    logo_url VARCHAR(255),
    CONSTRAINT pk_team PRIMARY KEY (id)
);