CREATE TABLE league
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    type     VARCHAR(255),
    logo_url VARCHAR(255),
    rapid_id INTEGER,
    CONSTRAINT pk_league PRIMARY KEY (id)
);