CREATE TABLE player
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    age         INTEGER,
    nationality VARCHAR(255),
    height      INTEGER,
    weight      INTEGER,
    injured     BOOLEAN,
    photo_url   VARCHAR(255),
    rapid_id    INTEGER,
    team_id     INTEGER,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

ALTER TABLE player
    ADD CONSTRAINT FK_PLAYER_ON_TEAMID FOREIGN KEY (team_id) REFERENCES team (id);